
default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_destribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:483147718309:android:1d5c388803240b6d53374c",
      firebase_cli_token:"1//03JbeMaVai41cCgYIARAAGAMSNwF-L9Ir92h_mBiPfixbyGV560yS_VqJ_9GQgavqS07ABBtEHDOe4VbqbMJZecL4dAeIc3w9jR4",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "abdallhesam100@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution"
    )
  end
end
